##
# Makefile
#
# Date: November 13, 2016
# Authors: Brandon Perez (bmperez)
# 		   Devon White (dww)
# 		   Yiyi Zhang (yiyz)
#
# This Makfile handles performing various tasks for blob detector project,
# and compiling the reference implementation.
##

################################################################################
# Configuration
################################################################################

# The directory containing the MATLAB reference implementation
MATLAB_DIR = matlab

# The URL of the headlight data set on Google Drive, and its directory location
HEADLIGHT_DATASET_URL = https://drive.google.com/uc?export=download&id=0B_mYgTecD_1nLTNwOTlVRG9HYU0
HEADLIGHT_DATASET_ARCHIVE = headlight_images.zip
HEADLIGHT_DATASET_DIR = $(MATLAB_DIR)/headlight_images

################################################################################
# Targets
################################################################################

# These targets don't correspond to generated files
.PHONY: all default fetch-dataset clean help

# The default target for the Makefile is to display the help message
all default: help

# User-facing target to fetch the headlight image dataset
fetch-dataset: $(HEADLIGHT_DATASET_DIR)

# Fetch the headlight dataset from Google Drive, and unzip it into the MATLAB
# directory.
$(HEADLIGHT_DATASET_DIR):
	wget '$(HEADLIGHT_DATASET_URL)' -O $(HEADLIGHT_DATASET_ARCHIVE)
	unzip $(HEADLIGHT_DATASET_ARCHIVE) -d $(MATLAB_DIR)
	rm -f $(HEADLIGHT_DATASET_ARCHIVE)

# Cleanup all of the intermediate files generated by the Makefile
clean:
	rm -rf $(HEADLIGHT_DATASET_DIR)

# Display a help message about how to use this Makefile to the user
help:
	@printf "Blob Detector Makefile: Help\n"
	@printf "\n"
	@printf "Usage:\n"
	@printf "\tmake [variable ...] target\n"
	@printf "\n"
	@printf ""
	@printf "Targets:\n"
	@printf "\tfetch-dataset\n"
	@printf "\t    Fetches the images for testing the MATLAB blob detector,\n"
	@printf "\t    putting the images in '$(HEADLIGHT_DATASET_DIR)'.\n"
